export const pageConfigs = {
  lifestyle: {
    showButton1: true,
    showButton2: false,
    showInput: true,
    titleButton1: "Once",
    titleButton2: "",
    placeholderInput: "Add to count",
    highlightButton1: true,
    highlightButton2: false,
  },
  interpersonal: {
    showButton1: true,
    showButton2: true,
    showInput: false,
    titleButton1: "yesterday",
    titleButton2: "today",
    placeholderInput: "",
    highlightButton1: false,
    highlightButton2: true,
  },
  financial: {
    showButton1: false,
    showButton2: false,
    showInput: true,
    titleButton1: "",
    titleButton2: "",
    placeholderInput: "Add an amount",
    highlightButton1: false,
    highlightButton2: false,
  },
  external: {
    showButton1: true,
    showButton2: false,
    showInput: false,
    titleButton1: "today",
    titleButton2: "",
    placeholderInput: "",
    highlightButton1: true,
    highlightButton2: false,
  },
};
